config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations'
  }

  devise_scope :user do
    get 'send_mail' => 'devise/registrations#email_sended'
    get 'complete_registration' => 'devise/registrations#complete'
  end

  resources :users, param: :url_token do
    collection do
      get :search
    end
    member do
      get :following, :followers
    end
  end

  resources :events, param: :url_token, shallow: true do
    resources :comments, only: [:create, :destroy]
    collection do
      get :search, :autocomplete_search, :golf_course_info
    end
    member do
      patch :invite
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :participants, only: [:create, :destroy]
  resources :notifications, only: :index
  resources :event_invitations, only: :update

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  admin                  :boolean          default(FALSE)
#  avatar                 :string(255)
#  average_score          :integer
#  birth_date             :date
#  confirmation_sent_at   :datetime
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  guest                  :boolean          default(FALSE)
#  introduction           :text(65535)
#  play_type              :integer
#  rate                   :float(24)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  sex                    :integer          default("未設定")
#  unconfirmed_email      :string(255)
#  url_token              :string(255)
#  username               :string(255)      default(""), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  prefecture_id          :integer
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  mount_uploader :avatar, AvatarUploader

  has_many :events, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_events, through: :likes, source: :event
  has_many :participants, dependent: :destroy
  has_many :participated_events, through: :participants, source: :event
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :active_notifications, class_name: 'Notification',
                                  foreign_key: 'visitor_id',
                                  dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification',
                                   foreign_key: 'visited_id',
                                   dependent: :destroy
  has_many :invited_events, class_name: 'EventInvitation',
                            foreign_key: 'invited_user_id',
                            dependent: :destroy

  before_validation :generate_url_token, on: :create

  validates :username, presence: true, length: { maximum: 50 }
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    length: { maximum: 255 }
  validates :url_token, presence: true, uniqueness: true
  validates :introduction, length: { maximum: 240 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :async

  scope :invitable_users, lambda { |event|
    joins('INNER JOIN relationships ON users.id = relationships.followed_id')
      .where(relationships: { follower_id: event.user_id })
      .where.not(relationships:
          { followed_id:
            Notification
              .where(event_id: event.id)
              .where(action: Event::INVITE_ACTION)
              .select('visited_id') })
  }

  enum sex: {
    未設定: 0, 男性: 1, 女性: 2
  }

  enum play_type: {
    アスリート系: 1, エンジョイ系: 2, 初心者: 3
  }

  enum average_score: {
    シングル（70台）: 1, けっこう上手い（80台）: 2, わりと上手い（90台）: 3,
    まあまま（100台）: 4, まだまだ（110〜120台）: 5, ぜんぜん（130台〜）: 6
  }

  FOLLOW_ACTION = 'follow'

  def to_param
    url_token
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end

  def create_notification_follow!(current_user)
    follow_notification = Notification.search_notification(current_user.id, id, nil, FOLLOW_ACTION)

    if follow_notification.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: FOLLOW_ACTION
      )
      notification.save if notification.valid?
    end
  end

  def self.ages
    ages = {
      age10: { id: 1, min: 0, max: 19, name: '10代以下' },
      age20: { id: 2, min: 20, max: 29, name: '20代' },
      age30: { id: 3, min: 30, max: 39, name: '30代' },
      age40: { id: 4, min: 40, max: 49, name: '40代' },
      age50: { id: 5, min: 50, max: 59, name: '50代' },
      age60: { id: 6, min: 60, max: 200, name: '60代以上' }
    }
  end

  def get_ages
    ages_name = '不明'
    if birth_date?
      age = (Date.today.strftime('%Y%m%d').to_i - birth_date.strftime('%Y%m%d').to_i) / 10_000
      User.ages.each_value do |value|
        min = value[:min].to_i
        max = value[:max].to_i
        ages_name = value[:name] if age.between?(min, max)
      end
    end
    ages_name
  end

  private

  def generate_url_token
    self.url_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  protected

  def after_confirmation_path_for(_resource_name, _resource)
    complete_registration_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(resource)
    edit_user_registration_path(resource)
  end

  def after_inactive_sign_up_path_for(_resource)
    send_mail_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :admin_user, only: :destroy

  MAX_PAGE = 20

  def index
    @search_item_hash = { prefecture_id: 0, ages: 0, age_min: 0, age_max: 0, sex: 0, play_type: 0 }
    # ログインしている場合はログインユーザーを検索結果に含めない
    @users = if user_signed_in?
               User.where.not(admin: true, id: current_user.id)
             else
               User.where.not(admin: true)
             end
    pagination_users(@users)
  end

  def search
    # 画面の各種検索条件を取得する
    search_item_hash = if params[:search_item_hash].is_a?(String)
                         JSON.parse(params[:search_item_hash])
                       else
                         params[:search_item_hash].permit!.to_h
                       end
    prefecture_id = params[:prefecture_id] || search_item_hash['prefecture_id']
    ages = params[:ages] || search_item_hash['ages']
    age_min = params[:age_min] || search_item_hash['age_min']
    age_max = params[:age_max] || search_item_hash['age_max']
    sex = params[:sex] || search_item_hash['sex']
    play_type = params[:play_type] || search_item_hash['play_type']

    # 検索条件の設定
    conditions = [
      { admin: false }
    ]

    # 都道府県
    if prefecture_id.to_i.between?(1, Prefecture.count)
      conditions.push(
        { prefecture_id: prefecture_id }
      )
    end

    # 年代
    if ages.to_i.between?(1, User.ages.count)
      birth_date_start = Date.today.prev_year(age_max.to_i)
      birth_date_end = Date.today.prev_year(age_min.to_i)

      conditions.push(
        { birth_date: birth_date_start..birth_date_end }
      )
    end

    # 性別
    if sex.to_i.between?(1, User.sexes.count - 1)
      conditions.push(
        { sex: sex }
      )
    end

    # プレータイプ
    if play_type.to_i.between?(1, User.play_types.count)
      conditions.push(
        { play_type: play_type }
      )
    end

    users = conditions.inject(User, &:where)

    # ログインユーザーは除外する
    users.where.not(id: current_user.id) if user_signed_in?

    @users = users

    pagination_users(@users)

    # 画面の検索条件を更新する
    @search_item_hash = { prefecture_id: prefecture_id, ages: ages, age_min: age_min, age_max: age_max,
                          sex: sex, play_type: play_type }
    render action: :index
  end

  def show
    find_user

    @events = @user.events.order(event_date: :desc).page(params[:event_page]).per(MAX_PAGE)
    @participated_events = @user.participated_events.order(event_date: :desc).page(params[:participated_event_page]).per(MAX_PAGE)
    @liked_events = @user.liked_events.order(event_date: :desc).page(params[:liked_event_page]).per(MAX_PAGE)
  end

  def following
    find_user

    @following = @user.following.page(params[:page]).per(MAX_PAGE)
  end

  def followers
    find_user

    @followers = @user.followers.page(params[:page]).per(MAX_PAGE)
  end

  def destroy
    find_user.destroy
    flash[:notice] = 'ユーザーは正常に削除されました'
    redirect_to users_path
  end

  private

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

  def find_user
    @user = User.find_by!(url_token: params[:url_token])
  end

  def pagination_users(users)
    # 検索結果の件数を設定
    @user_count = users.count
    # ページネーション
    @users = Kaminari.paginate_array(users).page(params[:page]).per(MAX_PAGE)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build) do |f| %>
  <%= hidden_field_tag :followed_id, object.id %>
  <%= f.submit "フォロー", class: "btn userList-follow bg-light text-info" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if user_signed_in? %>
  <% unless object == current_user %>
    <div class="follow-form user-<%= object.id %>" style="width: 100%;">
      <% if current_user.following?(object) %>
        <%= render 'unfollow', object: object %>
      <% else %>
        <%= render 'follow', object: object %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/users/_followlist.html.erb
<div class="page">
  <div class="user-index-panel">
    <div class="text-white text-left">
      <h4>
        フォローリスト
      </h4>
    </div>
    <div class="followlist-tab">
      <ul class="nav nav-tabs">
        <% following_tab_active = "active" unless following.nil? %>
        <% followers_tab_active = "active" unless followers.nil? %>
        <li class="nav-item followlist-tabitem">
          <%= link_to following_user_path(user),
            class: "nav-link #{following_tab_active}" do %>
            フォロー(<%= user.following.count.to_s(:delimited) %>)
          <% end %>
        </li>
        <li class="nav-item followlist-tabitem">
          <%= link_to followers_user_path(user),
            class: "nav-link #{followers_tab_active}" do %>
            フォロワー(<%= user.followers.count.to_s(:delimited) %>)
          <% end %>
        </li>
      </ul>
    </div>

    <% if !following.nil? %>
      <%= render partial: 'users/userlist', locals: { users: following } %>
    <% elsif !followers.nil? %>
      <%= render partial: 'users/userlist', locals: { users: followers } %>
    <% end %>
  </div>
</div>

app/views/users/_search_form.html.erb
<div class="search-box bg-white">
  <div class="text-info search-title">
    ゴル友を探す(<%= user_count %>)
  </div>
  <table class="search-table">
    <tr class="search-tr">
      <td class="search-item-head">
        <div>
          エリア
        </div>
      </td>
      <td class="search-item-body">
        <div>
          <%= form_with(url: search_users_path, method: :get, local: true, id:'prefecture_select_form') do |f| %>
            <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name,
              { include_blank: '指定なし', prompt: '指定なし',
                selected: "#{@search_item_hash[:prefecture_id].to_i }" },
              { class: 'search-item-select btn btn-info btn-block' } %>
            <%= f.hidden_field :search_item_hash, value: @search_item_hash.to_json %>
            <%= f.submit class: 'search-item-btn-none' %>
          <% end %>
        </div>
      </td>
    </tr>
    <tr class="search-tr">
      <td class="search-item-head">
        <div>
          年代
        </div>
      </td>
      <td class="search-item-body">
        <div>
          <%= link_to search_users_path(:ages => 0, :search_item_hash => @search_item_hash),
            class: "text-info #{@search_item_hash[:ages].to_i == 0 ? 'search-item-selected' : ''}" do %>
            指定なし
          <% end %>
        </div>
        <% User.ages.each_value do |age| %>
          <div>
            <%= link_to search_users_path(:ages => age[:id], :age_min => age[:min], :age_max => age[:max],
              :search_item_hash => @search_item_hash),
              class: "text-info #{@search_item_hash[:ages].to_i == age[:id] ? 'search-item-selected' : ''}" do %>
              <%= age[:name] %>
            <% end %>
          </div>
        <% end %>
      </td>
    </tr>
    <tr class="search-tr">
      <td class="search-item-head">
        <div>
          性別
        </div>
      </td>
      <td class="search-item-body">
        <div>
          <%= link_to search_users_path(:sex => 0, :search_item_hash => @search_item_hash),
            class: "text-info #{@search_item_hash[:sex].to_i == 0 ? 'search-item-selected' : ''}" do %>
            指定なし
          <% end %>
        </div>
        <% User.sexes.each do |sex| %>
          <% unless sex[1].to_i == 0 %>
          <div>
            <%= link_to search_users_path(:sex => sex[1], :search_item_hash => @search_item_hash),
              class: "text-info #{@search_item_hash[:sex].to_i == sex[1].to_i ? 'search-item-selected' : ''}" do %>
              <%= sex[0] %>
            <% end %>
          </div>
          <% end %>
        <% end %>
      </td>
    </tr>
    <tr class="search-tr">
      <td class="search-item-head">
        <div>
          プレータイプ
        </div>
      </td>
      <td class="search-item-body">
        <div>
          <%= link_to search_users_path(:play_type => 0, :search_item_hash => @search_item_hash),
            class: "text-info #{@search_item_hash[:play_type].to_i == 0 ? 'search-item-selected' : ''}" do %>
            指定なし
          <% end %>
        </div>
        <% User.play_types.each do |play_type| %>
          <div>
            <%= link_to search_users_path(:play_type => play_type[1], :search_item_hash => @search_item_hash),
              class: "text-info #{@search_item_hash[:play_type].to_i == play_type[1].to_i ? 'search-item-selected' : ''}" do %>
              <%= play_type[0] %>
            <% end %>
          </div>
        <% end %>
      </td>
    </tr>
  </table>
</div>

<script>
$(document).ready(function(){
  $("#prefecture_id").change(function(){
    $('#prefecture_select_form').submit();
  });
});
</script>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: object.id),
              html: { method: :delete }) do |f| %>
  <%= hidden_field_tag :user_id, object.id %>
  <%= f.submit "フォロー中", class: "btn userList-follow bg-info text-white" %>
<% end %>

app/views/users/_user_card.html.erb
<div class="userList-card">
  <div class="float-left userList-image">
    <%= link_to user_path(user_card) do %>
      <% if user_card.avatar?%>
        <%= image_tag user_card.avatar.url, class: 'avatar-img rounded-circle' %>
      <% else %>
        <%= image_tag 'fallback/default_user_avatar.png', class: 'avatar-img rounded-circle' %>
      <% end %>
    <% end %>
  </div>
  <div class="d-block d-lg-none float-left">
    <div class="userList-body-name text-left pt-4 pl-3">
      <%= link_to user_path(user_card) do %>
        <%= user_card.username %>
      <% end %>
    </div>
  </div>

  <div class="float-left userList-body">
    <div class="d-none d-lg-block">
      <div class="userList-body-name">
        <%= link_to user_path(user_card) do %>
          <%= user_card.username %>
        <% end %>
      </div>
    </div>
    <div class="userList-body-intro">
      <%= link_to user_path(user_card) do %>
        <%= user_card.introduction %>
      <% end %>
    </div>
    <div class="userList-body-detail">
      エリア：<%= user_card.prefecture.name if !user_card.prefecture.nil? %>
    </div>
    <div class="userList-body-detail">
      年代：<%= user_card.get_ages %>&emsp;
      性別：<%= user_card.sex %>
    </div>
    <div class="userList-body-detail">
      プレータイプ：<%= user_card.play_type %>
    </div>
    <div class="userList-body-detail">
      平均スコア：<%= user_card.average_score %>
    </div>
  </div>

  <% if user_signed_in? %>
    <div class="float-left userList-btn mt-2">
      <%= render 'users/follow_form', object: user_card %>
      <% if current_user.admin? && user_card != current_user %>
        <a class="btn userList-delete bg-danger text-white" data-toggle="modal"
          data-target="#modal-<%= ApplicationHelper::DELETE_USER_MODAL_MODE + user_card.id.to_s %>">
          削除&nbsp;<i class="fa fa-trash" aria-hidden="true"></i>
        </a>
      <% end %>
    </div>
  <% end %>
</div>
<%= render 'layouts/modal',
  {modal_id: ApplicationHelper::DELETE_USER_MODAL_MODE + user_card.id.to_s,
  mode: ApplicationHelper::DELETE_USER_MODAL_MODE, object: user_card} %>

app/views/users/_user_card_mini.html.erb
<%= link_to user_path(user_card) do %>
  <% if user_card.avatar?%>
    <%= image_tag user_card.avatar.url, class: 'avatar-img-mini rounded-circle' %>
  <% else %>
    <%= image_tag 'fallback/default_user_avatar.png', class: 'avatar-img-mini rounded-circle' %>
  <% end %>
  <span class="user-name">
    <%= user_card.username %>
  </span>
<% end %>

app/views/users/_user_card_mini_nolink.html.erb
<% if user_card.avatar?%>
  <%= image_tag user_card.avatar.url, class: 'avatar-img-mini rounded-circle' %>
<% else %>
  <%= image_tag 'fallback/default_user_avatar.png', class: 'avatar-img-mini rounded-circle' %>
<% end %>
<span class="user-name">
  <%= user_card.username %>
</span>

app/views/users/_userlist.html.erb
<div class="text-left">
  <%= paginate(users) %>
</div>

<div class="users">
  <%= render partial: 'users/user_card', collection: users, as: :user_card %>
</div>

<div class="text-left">
  <%= paginate(users) %>
</div>

app/views/users/followers.html.erb
<% provide(:title, 'フォロワー') %>

<%= render partial: 'users/followlist', locals: { user: @user, following: nil, followers: @followers } %>

app/views/users/following.html.erb
<% provide(:title, 'フォロー') %>

<%= render partial: 'users/followlist', locals: { user: @user, following: @following, followers: nil } %>

app/views/users/index.html.erb
<% provide(:title, 'ゴル友を探す') %>

<div class="page">
  <div class="user-index-panel">
    <div class="search-form">
      <%= render partial: 'users/search_form', locals: { user_count: @user_count } %>
    </div>

    <%= render partial: 'users/userlist', locals: { users: @users } %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<%= javascript_include_tag 'users.js' %>

<div class="user-page">
  <div class="user-detail-panel">
    <div class="user-detail">
      <div class="user-profile">
        <h3 class="text-secondary">プロフィール</h3>
        <div class="user-profile-follow-form">
          <%= render 'users/follow_form', object: @user %>
        </div>
        <div class="user-profile-image">
          <% if @user.avatar?%>
            <%= image_tag @user.avatar.url, class: 'avatar-img-big rounded-circle' %>
          <% else %>
            <%= image_tag 'fallback/default_user_avatar.png', class: 'avatar-img-big rounded-circle' %>
          <% end %>
        </div>
        <div class="user-profile-contents">
          <div class="user-profile-item">
            <span class="text-info">ユーザー名</span>
            <br>
            <p class="pl-2">
              <%= @user.username %>
            </p>
          </div>
          <div class="user-profile-item">
            <span class="text-info">エリア</span>
            <br>
            <p class="pl-2">
              <%= @user.prefecture.name if !@user.prefecture.nil? %>
            </p>
          </div>
          <div class="user-profile-item">
            <span class="text-info">年代</span>
            <br>
            <p class="pl-2">
              <%= @user.get_ages %>
            </p>
          </div>
          <div class="user-profile-item">
            <span class="text-info">性別</span>
            <br>
            <p class="pl-2">
              <%= @user.sex %>
            </p>
          </div>
          <div class="user-profile-item">
            <span class="text-info">プレータイプ</span>
            <br>
            <p class="pl-2">
              <%= @user.play_type %>
            </p>
          </div>
          <div class="user-profile-item">
            <span class="text-info">アベレージスコア</span>
            <br>
            <p class="pl-2">
              <%= @user.average_score %>
            </p>
          </div>
          <div class="user-profile-item">
            <span class="text-info">コメント</span>
            <br>
            <p class="pl-2">
              <%= @user.introduction %>
            </p>
          </div>
          <div class="user-profile-item">
            <span class="text-info">フォロー</span>
            <br>
            <p class="pl-2">
              <%= link_to following_user_path(@user) do %>
                <%= @user.following.count.to_s(:delimited) %>
              <% end %>
            </p>
          </div>
          <div class="user-profile-item">
            <span class="text-info">フォロワー</span>
            <br>
            <p class="pl-2">
              <%= link_to followers_user_path(@user) do %>
                <%= @user.followers.count.to_s(:delimited) %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="event-box">
      <ul class="nav nav-tabs" id="profile-tablist" role="tablist">
        <li class="nav-item profile-tabitem">
          <a href="#tab1" id="event-tab" class="nav-link" data-toggle="tab" aria-selected="true">
            主催イベント(<%= @user.events.count.to_s(:delimited) %>)
          </a>
        </li>
        <li class="nav-item profile-tabitem">
          <a href="#tab2" id="participated-event-tab" class="nav-link" data-toggle="tab" aria-selected="true">
            参加イベント(<%= @user.participated_events.count.to_s(:delimited) %>)
          </a>
        </li>
        <% if current_user?(@user) %>
        <li class="nav-item profile-tabitem">
          <a href="#tab3" id="liked-event-tab" class="nav-link" data-toggle="tab" aria-selected="true">
            気になるイベント(<%= @user.liked_events.count.to_s(:delimited) %>)
          </a>
        </li>
        <% end %>
      </ul>
      <div class="tab-content mt-3" id="profile-tabContent">
        <div id="tab1" class="tab-pane" aria-labelledby="event-tab">
          <% if @events.any? %>
            <%= paginate(@events, :param_name => "event_page") %>
            <ul class="events">
              <%= render partial: "events/event_card", collection: @events, as: :event_card,
                locals: { event_card_mode: ApplicationHelper::NORMAL_EVENT_CARD_MODE } %>
            </ul>
            <%= paginate(@events, :param_name => "event_page") %>
          <% else %>
            <span class="text-white">主催イベントはありません</span>
          <% end %>
        </div>
        <div id="tab2" class="tab-pane" ia-labelledby="participated-event-tab">
          <% if @participated_events.any? %>
            <%= paginate(@participated_events, :param_name => "participated_event_page") %>
            <ul class="events">
              <%= render partial: "events/event_card", collection: @participated_events, as: :event_card,
                locals: { event_card_mode: ApplicationHelper::PARTICIPATED_EVENT_CARD_MODE }%>
            </ul>
            <%= paginate(@participated_events, :param_name => "participated_event_page") %>
          <% else %>
            <span class="text-white">参加イベントはありません</span>
          <% end %>
        </div>
        <% if current_user?(@user) %>
        <div id="tab3" class="tab-pane" ia-labelledby="liked-event-tab">
          <% if @liked_events.any? %>
            <%= paginate(@liked_events, :param_name => "liked_event_page") %>
            <ul class="events">
              <%= render partial: "events/event_card", collection: @liked_events, as: :event_card,
                locals: { event_card_mode: ApplicationHelper::LIKED_EVENT_CARD_MODE }%>
            </ul>
            <%= paginate(@liked_events, :param_name => "liked_event_page") %>
          <% else %>
            <span class="text-white">気になるイベントはありません</span>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
    
  </div>
</div>