config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations'
  }

  devise_scope :user do
    get 'send_mail' => 'devise/registrations#email_sended'
    get 'complete_registration' => 'devise/registrations#complete'
  end

  resources :users, param: :url_token do
    collection do
      get :search
    end
    member do
      get :following, :followers
    end
  end

  resources :events, param: :url_token, shallow: true do
    resources :comments, only: [:create, :destroy]
    collection do
      get :search, :autocomplete_search, :golf_course_info
    end
    member do
      patch :invite
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :participants, only: [:create, :destroy]
  resources :notifications, only: :index
  resources :event_invitations, only: :update

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                   :bigint           not null, primary key
#  address              :string(255)
#  content              :text(65535)
#  end_time             :time
#  event_date           :date
#  image                :string(255)
#  maximum_participants :integer          default(0)
#  place                :string(255)
#  start_time           :time
#  title                :string(255)
#  url_token            :string(255)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  course_id            :integer
#  user_id              :bigint
#
# Indexes
#
#  index_events_on_user_id                 (user_id)
#  index_events_on_user_id_and_created_at  (user_id,created_at)
#
class Event < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  default_scope -> { order(event_date: :desc) }

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :participants, dependent: :destroy
  has_many :participated_users, through: :participants, source: :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :event_invitations, dependent: :destroy

  before_validation :generate_url_token, on: :create

  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true, length: { maximum: 1000 }
  validates :place, presence: true, length: { maximum: 100 }
  validates :event_date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :maximum_participants, presence: true, numericality: { only_integer: true }
  validate :maximum_participants_check
  validates :user_id, presence: true
  validates :url_token, presence: true, uniqueness: true
  validate :event_date_check
  validate :start_end_check

  LIKE_ACTION = 'like'.freeze
  PARTICIPATE_ACTION = 'participate'.freeze
  COMMENT_ACTION = 'comment'.freeze
  INVITE_ACTION = 'invite'.freeze
  CLOSE_ACTION = 'close'.freeze

  def to_param
    url_token
  end

  def like(user)
    likes.create(user_id: user.id)
  end

  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end

  def already_liked?(user)
    liked_users.include?(user)
  end

  def participate(user)
    participants.create(user_id: user.id)
  end

  def stop_participate(user)
    participants.find_by(user_id: user.id).destroy
  end

  def already_participated?(user)
    participated_users.include?(user)
  end

  def create_notification_invite!(user_id)
    invite_notification = Notification.search_notification(user.id, user_id, id, INVITE_ACTION)

    if invite_notification.blank?
      notification = user.active_notifications.new(
        visited_id: user_id,
        event_id: id,
        action: INVITE_ACTION
      )
      if notification.valid?
        notification.save!

        event_invitation = EventInvitation.new(
          event_id: id,
          invited_user_id: user_id,
          invitation_status: EventInvitation::UNCONFIRMED
        )
        event_invitation.save! if event_invitation.valid?
      end
    end
  end

  private

  def generate_url_token
    self.url_token = SecureRandom.urlsafe_base64
  end

  def maximum_participants_check
    if maximum_participants.nil? ||
       !maximum_participants.between?(2, 50)
      errors.add(:maximum_participants,
                 :greater_than_or_equal_to_less_than_or_equal_to, { minimum: 2, maximum: 50 })
    end
  end

  def event_date_check
    errors.add(:event_date, :after_than_today) if event_date < Date.today
  end

  def start_end_check
    late_time = [start_time, end_time].compact.max
    if !late_time.nil? && late_time == start_time
      errors.add(:end_time, :after_than_start_time)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include CommonActions

  before_action :authenticate_user!, only: %i[create destroy]
  before_action :correct_user, only: :destroy

  MAX_PAGE = 20

  def index
    initial_search
  end

  def new
    @event = current_user.events.build if user_signed_in?
  end

  def show
    # イベントが見つからない場合は例外を発生させる
    @event = Event.find_by!(url_token: params[:url_token])
    @like = Like.new
    @comments = @event.comments.order(created_at: :desc)
    @comment = Comment.new
    @wheather_condition = []

    course_info = RakutenWebService::Gora::CourseDetail.search(golfCourseId: @event.course_id)
    begin
      unless course_info.nil?
        course_info_first = course_info.first
        @route_map_url = course_info_first['routeMapUrl']
        latitude = course_info_first['latitude']
        longitude = course_info_first['longitude']

        wheatherforecast = WeatherForecast.new(latitude, longitude)
        @wheather_condition = wheatherforecast.weather_condition(@event.event_date)
      end
    rescue StandardError => e
      logger.debug(e.backtrace.join("\n"))
    end

    # 主催者の場合、イベントに参加していない招待可能なユーザーを取得。
    if user_signed_in?
      if current_user.id == @event.user_id
        @invitable_users = User.invitable_users(@event)
      end
    end
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      current_user.participants.create(event_id: @event.id)
      flash[:notice] = 'イベントを作成しました'
      redirect_to event_path(@event)
    else
      render 'new'
    end
  end

  def destroy
    @event.destroy
    flash[:notice] = 'イベントを削除しました'
    path = Rails.application.routes.recognize_path(request.referer)

    if path[:controller] == 'events'
      redirect_to root_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @event = Event.find_by(url_token: params[:url_token])
  end

  def update
    @event = Event.find_by(url_token: params[:url_token])
    if @event.update(event_params)
      flash[:notice] = 'イベントを更新しました'
      redirect_to event_path(@event)
    else
      render 'edit'
    end
  end

  def search
    search_events

    render action: :index
  end

  def autocomplete_search
    places = {}

    if params[:term]
      courses = RakutenWebService::Gora::Course.search(keyword: params[:term].to_s)
      courses.each do |course|
        golf_course_id = course['golfCourseId']
        golf_course_abbr = course['golfCourseAbbr']
        golf_course_abbr = golf_course_abbr.to_s + '[' + golf_course_id.to_s + ']'
        places[golf_course_id] = golf_course_abbr
      end
    end
    render json: places.to_json
  end

  def golf_course_info
    course_info = RakutenWebService::Gora::CourseDetail.search(golfCourseId: params[:course_id])

    unless course_info.nil?
      course_info_first = course_info.first
      address = course_info_first['address']
      golf_course_image_url = course_info_first['golfCourseImageUrl1']
      respond_to do |format|
        format.json do
          render json: { address: address,
                         golf_course_image_url: golf_course_image_url }, status: :ok
        end
      end
    end
  end

  def invite
    @event = Event.find_by!(url_token: params[:url_token])
    params[:event][:user_ids].each do |user_id|
      @event.create_notification_invite!(user_id) if user_id.to_i >= 1
    end

    flash[:notice] = 'ゴル友を招待しました'
    redirect_to event_path(@event)
  end

  private

  def event_params
    params.require(:event).permit(:title, :content, :place, :address, :maximum_participants, :image,
                                  :remote_image_url, :event_date, :start_time, :end_time, :course_id)
  end

  def correct_user
    @event = current_user.events.find_by(url_token: params[:url_token])
    if @event.nil? && current_user.admin?
      @event = Event.find_by(url_token: params[:url_token])
    end
    redirect_to root_url if @event.nil?
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def date_wday(date)
    date.to_s + '(' + %w[日 月 火 水 木 金 土][date.wday] + ')'
  end

  def format_time(time)
    time.strftime("%H:%M")
  end
end

app/views/events/_comment_form.html.erb
<div class="comment-form">
  <% if user_signed_in? %>
    <div id="comment-content">
      <%= form_with(model: [object, @comment]) do |f| %>
        <%= hidden_field_tag :event_id, object.id %>
        <%= f.text_area :content, class: "base-textarea", id: "input-content-area",
          rows: 4,
          placeholder: "コメントする..." %>
        <div class="comment-btn" id="comment-btn">
          <p class="float-left text-danger" id="content-counter"></p>
          <%= button_tag(id: "send-comment", class: "btn float-right pt-0",
            style: "font-size:1em;",
            disabled: true) do %>
            <i class="fa fa-paper-plane" aria-hidden="true"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div id="comment-body" class="text-left">
    <%= render 'events/comment', comments: @comments %>
  </div>
</div>

app/views/events/_event_card.html.erb
<div class="eventList-card" id="eventList-card-<%= event_card.id %>">
  <div class="eventList-image">
    <%= link_to event_path(event_card) do %>
      <% if event_card.image?%>
        <%= image_tag event_card.image.url, class: 'event-img-card' %>
      <% else %>
        <%= image_tag 'fallback/default_event_image.png', class: 'event-img-card' %>
      <% end %>
    <% end %>
  </div>

  <div class="eventList-body">
    <div class="eventList-body-title" id="eventList-body-title-<%= event_card.id %>">
      <%= link_to event_path(event_card) do %>
        <%= event_card.title %>
      <% end %>
    </div>

    <div class="eventList-body-item">
      主催者　：
      <%= link_to user_path(event_card.user) do %>
        <%= event_card.user.username %>
      <% end %>
    </div>

    <div class="eventList-body-item">
      開催日　：<%= date_wday(event_card.event_date) %>
    </div>

    <div class="eventList-body-item">
      場所　　：<%= event_card.place %>
    </div>

    <div class="eventList-body-item">
      住所　　：
      <% if event_card.address %>
        <%= link_to(event_card.address,
          "https://www.google.com/maps/search/?api=1&query=#{event_card.address}",
          :target=>["_blank"]) %>
      <% end %>
    </div>

    <div class="eventList-body-item">
      参加人数：
      <% if event_card.participants.count == event_card.maximum_participants %>
      <span class="text-danger">
      <% else %>
      <span>
      <% end %>
        <%= event_card.participants.count %>／<%= event_card.maximum_participants %>
      </span>
    </div>
  </div>

  <div class="eventList-btn" id="eventList-btn-<%= event_card.id %>">
    <% if event_card.event_date < Date.today %>
      <div class="w-100 font-weight-bold text-center text-danger">
        終了しました
      </div>
    <% end %>
    <% if user_signed_in? %>
      <%= render 'events/like_form', object: event_card %>
      <% if current_user?(event_card.user) || current_user.admin? %>
        <% if current_user?(event_card.user) %>
          <%= link_to edit_event_path(event_card),
            class: "btn base-btn mt-2 btn-secondary base-btn text-white" do %>
            &nbsp;&nbsp;編集&nbsp;<i class="fa fa-edit"></i>&nbsp;
          <% end %>
          <div class="d-none d-lg-block" style="height:0px;">
            <br>
          </div>
        <% end %>
        <a class="btn base-btn mt-2 bg-danger text-white" data-toggle="modal"
          data-target="#modal-<%= event_card_mode.to_s + ApplicationHelper::DELETE_EVENT_MODAL_MODE + event_card.id.to_s %>">
          &nbsp;&nbsp;削除&nbsp;<i class="fa fa-trash" aria-hidden="true"></i>&nbsp;
        </a>
      <% end %>
    <% end %>
  </div>
</div>
<%= render 'layouts/modal',
  {modal_id: event_card_mode.to_s + ApplicationHelper::DELETE_EVENT_MODAL_MODE + event_card.id.to_s,
  mode: ApplicationHelper::DELETE_EVENT_MODAL_MODE, object: event_card} %>

app/views/events/_event_form.html.erb
<% provide(:title, title) %>
<%= javascript_include_tag 'events.js' %>

<div class="page">
  <div class="mid-white-panel">
    <h2><%= title %></h2>

    <%= form_with(model: object, local: true) do |form| %>
      <div class="event-form-group">
        <%= render "shared/error_messages", resource: form.object %>
      </div>

      <div class="event-form-group">
        <%= form.label :title, "タイトル", class: "control-label" %>
        <%= form.text_field :title, class: "form-control", autofocus: true %>
      </div>

      <div class="event-form-group">
        <%= form.label :event_date, "日時", class: "control-label" %>
        <br>
        <%= form.date_field :event_date, value: (form.object.event_date || Time.now.strftime("%Y-%m-%d")),
          class: "form-control-select" %>
        <p class="mb-1"></p>
          <%= form.time_select :start_time, {default: Date.today + 7.hour,
            start_hour: 00, end_hour: 23, minute_step: 15},
            {class: "form-control-select btn-light"} %>
          〜
          <%= form.time_select :end_time, {default: Date.today + 17.hour,
            start_hour: 00, end_hour: 23, minute_step: 15},
            {class: "form-control-select btn-light"} %>
      </div>

      <div class="event-form-group">
        <%= form.label :place, "ゴルフ場", class: "control-label" %>
        <%= form.text_field :place, id: :place_id, placeholder: "入力に応じて候補が表示されます",
          class: "form-control" %>
        <%= form.hidden_field :course_id, id: :course_id %>
      </div>

      <div class="event-form-group">
        <%= form.label :address, "住所(任意)", class: "control-label" %>
        <%= form.text_field :address, id: :address_field, class: "form-control" %>
      </div>

      <div class="event-form-group">
        <%= form.label :maximum_participants, "最大参加可能人数", class: "control-label" %>
        <br>
        <%= form.number_field :maximum_participants, class: "form-control-select", value: 2, min:2 %>
      </div>

      <div class="event-form-group">
        <%= form.label :content, "詳細", class: "control-label" %>
        <%= form.text_area :content, class: "form-control", id: "input-detail-area", rows:15 %>
        <p class="float-left text-danger float-right" id="detail-counter"></p>
      </div>

      <div class="event-form-group">
        <%= form.label :image, "イメージ", class: "control-label" %>
        <div class="square-image">
          <% if object.image? %>
            <%= image_tag object.image.to_s, id: :img_prev %>
          <% else %>
            <%= image_tag "fallback/default_event_image.png", id: :img_prev %>
          <% end %>
          <%= form.hidden_field :image_cache %>
          <div class="mt-1">
            <label for="event_img">
              <span class="btn btn-outline-secondary">
                画像変更
              </span>
              <%= form.file_field :image, id: :event_img, class: "d-none" %>
              <%= form.hidden_field :remote_image_url %>
            </label>
          </div>
        </div>
      </div>

      <div class="event-form-group">
        <%= form.submit "更新", class: "btn btn-info btn-block text-white" %>
      </div>

    <% end %>
  </div>
</div>

app/views/events/_eventlist.html.erb
<div class="page">
  <div class="event-index-panel">

    <div class="mb-2">
      <%= render 'events/new_event_form' %>
    </div>

    <div class="search-form">
      <%= render partial: 'events/search_form', locals: { event_count: event_count } %>
    </div>

    <div class="bg-white p-2 mb-2" style="overflow:hidden;">
      <div class="float-left mr-2">
        [並び替え]
      </div>
      <div class="float-left mr-2">
        <%= sort_link(@q, :event_date, "開催日") %>
      </div>
      <div class="float-left">
        <%= sort_link(@q, :created_at, "登録順") %>
      </div>
    </div>

    <div class="text-left">
      <%= paginate(events) %>
    </div>

    <div class="events">
      <%= render partial: 'events/event_card', collection: events, as: :event_card,
        locals: { event_card_mode: ApplicationHelper::NORMAL_EVENT_CARD_MODE } %>
    </div>

    <div class="text-left">
      <%= paginate(events) %>
    </div>
  </div>
</div>

app/views/events/_like.html.erb
<%= form_with(model: object.likes.build) do |f| %>
  <%= hidden_field_tag :event_id, object.id %>
  <%= f.submit "  気になる  ", class: "btn base-btn bg-light text-info" %>
<% end %>

app/views/events/_like_form.html.erb
<% if user_signed_in? %>
  <% unless object.user.id == current_user.id %>
    <div class="like-form event-<%= object.id %> mt-2" style="width: 100%;">
      <% if object.already_liked?(current_user) %>
        <%= render 'events/unlike', object: object %>
      <% else %>
        <%= render 'events/like', object: object %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/events/_participants_form.html.erb
<div class="participants-list">
  <% if object.participated_users.any? %>
    <ul>
      <% object.participated_users.each do |user| %>
        <li><%= render 'users/user_card_mini', user_card: user %></li>
      <% end %>
    </ul>
  <% else %>
    <div class="text-left">
      参加者がいません
    </div>
  <% end %>
</div>

app/views/events/_participants_list_modal.html.erb
<div class="modal modal-default" id="participants-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        ゴル友を招待する
      </div>
      <div class="modal-body overflow-auto" style="height:300px">
        <p class="text-left">招待するゴル友を選択してください。</p>
          <div class="participants-list">
            <%= form_with(model: event, url: invite_event_path(event), local: true) do |f| %>
              <ul>
                <% users.each do |user| %>
                  <li>
                    <%= f.check_box :user_ids, { multiple: true }, user.id %>
                    <%= render 'users/user_card_mini_nolink', user_card: user %>
                  </li>
                <% end %>
              </ul>
              <div class="text-left">
                <%= f.submit "招待する", class: "btn base-btn bg-info text-white" %>
              </div>
            <% end %>
          </div>
        <br>
      </div>
      <div class="modal-footer" id="modal-btn">
        <button type="button" class="btn btn-sm" data-dismiss="modal">キャンセル</button>
      </div>
    </div>
  </div>
</div>

app/views/events/_participate.html.erb
<button type="button" class="btn base-btn bg-info text-white" data-toggle="modal"
  data-target="#modal-<%= ApplicationHelper::PARTICIPATE_EVENT_MODAL_MODE %>">参加する</button>
<%= render 'layouts/modal',
  {modal_id: ApplicationHelper::PARTICIPATE_EVENT_MODAL_MODE,
  mode: ApplicationHelper::PARTICIPATE_EVENT_MODAL_MODE, object: object} %>

app/views/events/_search_form.html.erb
<%= javascript_include_tag 'events.js' %>

<div class="search-box bg-white">
  <div class="text-info search-title">
    イベントを探す(<%= event_count %>)
  </div>
  <%= search_form_for @q, url: search_events_path do |f| %>
    <table class="search-table">
      <tr class="search-tr">
        <td class="search-item-head">
          <div>
            エリア
          </div>
        </td>
        <td class="search-item-body">
          <div>
            <%= f.collection_select :address_cont, Prefecture.all,
              :name, :name,
              { include_blank: '指定なし' },
              { class: 'search-item-select btn btn-info btn-block' } %>
          </div>
        </td>
      </tr>
      <tr class="search-tr">
        <td class="search-item-head">
          <div>
            開催日
          </div>
        </td>
        <td class="search-item-body">
          <div>
            <%= f.date_field :event_date_gteq, class: "search-item-select",
              value: ( f.object.event_date_gteq || Date.today) %>
            〜
            <%= f.date_field :event_date_lteq, class: "search-item-select" %>
          </div>
        </td>
      </tr>
      <tr class="search-tr">
        <td class="search-item-head">
          <div>
            ゴルフ場名
          </div>
        </td>
        <td class="search-item-body">
          <div class="w-100">
            <%= f.search_field :place_cont, id: :place_id, placeholder: "入力に応じて候補が表示されます",
              class: "search-item-text" %>
            <%= f.hidden_field :course_id, id: :course_id %>
          </div>
        </td>
      </tr>
      <tr class="search-tr">
        <td class="search-item-head">
          <div>
            参加可能人数
          </div>
        </td>
        <td class="search-item-body">
          <div>
            <%= f.number_field :maximum_participants_gteq, min: 2,
              class: "search-item-date",
              value: ( f.object.maximum_participants_gteq || 2) %>人以上〜
            <%= f.number_field :maximum_participants_lteq, min: 2, class: "search-item-date" %>人以下
          </div>
        </td>
      </tr>
      <tr>
        <td></td>
        <td class="pt-2">
          <div class="float-left">
          <%= f.submit "検索", class: "btn btn-info search-item-btn" %>
          </div>
          <div class="float-right">
          <input id="clear-btn" type="button" class="btn btn-secondary search-item-btn" value="クリア"/>
          </div>
        </td>
      </tr>
    </table>
  <% end %>
</div>

app/views/events/edit.html.erb
<%= render 'events/event_form', {object: @event, title: 'イベント編集'} %>

app/views/events/index.html.erb
<%= render partial: 'events/eventlist', locals: { events: @events, event_count: @event_count } %>

app/views/events/new.html.erb
<%= render 'events/event_form', {object: @event, title: "イベント作成"} %>

app/views/events/show.html.erb
<% provide(:title, "イベント詳細") %>
<%= javascript_include_tag 'comments.js' %>

<div class="page">
  <div class="wide-white-panel">
    <h2><%= @event.title %></h2>

    <div class="event-container">
      <div class="event-image">
        <% if @event.image?%>
          <%= image_tag @event.image.url, class: 'event-img' %>
        <% else %>
          <%= image_tag 'fallback/default_event_image.png', class: 'event-img' %>
        <% end %>
      </div>

      <div class="event-body">
        <table class="w-100">
          <tr>
            <td colspan="2">
              <div class="event-body-btn">
                <% if !current_user?(@event.user) %>
                  <%= render 'events/like_form', object: @event %>
                <% end %>
              </div>
              <% if user_signed_in? %>
                <% if current_user?(@event.user) || current_user.admin? %>
                  <div class="event-body-btn" id="event-delete-btn">
                      <a class="btn base-btn bg-danger text-white" data-toggle="modal"
                        data-target="#modal-<%= ApplicationHelper::DELETE_EVENT_MODAL_MODE %>">
                        削除&nbsp;<i class="fa fa-trash" aria-hidden="true"></i>
                      </a>
                    <%= render 'layouts/modal',
                      {modal_id: ApplicationHelper::DELETE_EVENT_MODAL_MODE,
                      mode: ApplicationHelper::DELETE_EVENT_MODAL_MODE, object: @event} %>
                  </div>
                  <% if current_user?(@event.user) %>
                    <div class="event-body-btn" id="event-edit-btn">
                      <%= link_to edit_event_path(@event), class: "btn btn-secondary base-btn text-white" do %>
                        編集&nbsp;<i class="fa fa-edit"></i>
                      <% end %>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td class="event-h-td">
              <div class="event-item user-name">主催者</div>
            </td>
            <td>
              <%= link_to user_path(@event.user) do %>
                <%= @event.user.username %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td class="event-h-td">
              <div class="event-item">日時</div>
            </td>
            <td>
              <%= date_wday(@event.event_date) %>&nbsp;&nbsp;
              <%= format_time(@event.start_time) %>〜
              <%= format_time(@event.end_time) %>
            </td>
          </tr>
          <tr>
            <td class="event-h-td">
              <div class="event-item">ゴルフ場</div>
            </td>
            <td>
              <% if @route_map_url.nil? %>
                <%= @event.place %>
              <% else %>
                <%= link_to(@event.place, @route_map_url, :target=>["_blank"]) %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td class="event-h-td">
              <div class="event-item">住所</div>
            </td>
            <td>
              <% if @event.address %>
                <%= link_to(@event.address,
                  "https://www.google.com/maps/search/?api=1&query=#{@event.address}",
                  :target=>["_blank"]) %>
              <% end %>
            </td>
          </tr>
          <% if @event.event_date >= Date.today %>
          <tr>
            <td class="event-h-td">
              <div class="event-item">当日の天気</div>
            </td>
            <td>
              <% unless @wheather_condition.present? %>
                天気情報が取得できませんでした
              <% else %>
                <table>
                  <% @wheather_condition.each do |weather| %>
                    <tr>
                      <td>
                        <%= weather[:time] %>
                      </td>
                      <td>
                        <%= weather[:description] %>
                      </td>
                    </tr>
                  <% end %>
                </table>
              <% end %>
            </td>
          </tr>
          <% end %>
          <tr valign="top">
            <td class="event-h-td">
              <div class="event-item">詳細</div>
            </td>
            <td>
              <%= simple_format(h(@event.content)) %>
            </td>
          </tr>
        </table>
      </div>
    </div>

    <% if @event.event_date < Date.today %>
      <div class="w-100 text-left text-danger">
        このイベントは終了しています。
      </div>
    <% else %>
      <% if user_signed_in? %>
        <% if !current_user?(@event.user) %>
          <% if @event.already_participated?(current_user) %>
            <div class="btn-field mb-2">
              <%= render 'events/stop_participate', object: @event %>
            </div>
          <% else %>
            <% if @event.participants.count == @event.maximum_participants %>
              <div class="w-100 text-left text-danger">
                定員に達したため参加できません
              </div>
            <% else %>
              <div class="btn-field mb-2">
                <%= render 'events/participate', object: @event %>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <div class="btn-field mb-2">
            <button type="button" class="btn base-btn bg-info text-white" data-toggle="modal"
              data-target="#participants-modal">ゴル友を招待</button>
          </div>
          <%= render 'events/participants_list_modal', { event: @event, users: @invitable_users } %>
        <% end %>
      <% end %>
    <% end %>

    <div>
      <ul class="nav nav-tabs">
        <li class="nav-item w-50">
          <a href="#tab1" id="participant-tab" class="nav-link active" data-toggle="tab">
            参加者(<%= @event.participants.count %>／<%= @event.maximum_participants %>)
          </a>
        </li>
        <li class="nav-item w-50">
          <a href="#tab2" id="comment-tab" class="nav-link" data-toggle="tab">
            コメント(<span id="comment-count"><%= @event.comments.count.to_s(:delimited) %></span>件)
          </a>
        </li>
      </ul>
      <div class="tab-content">
        <div id="tab1" class="tab-pane active">
          <%= render 'events/participants_form', object: @event %>
        </div>
        <div id="tab2" class="tab-pane">
          <%= render 'events/comment_form', object: @event %>
        </div>
      </div>
    </div>
  </div>
</div>