config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations'
  }

  devise_scope :user do
    get 'send_mail' => 'devise/registrations#email_sended'
    get 'complete_registration' => 'devise/registrations#complete'
  end

  resources :users, param: :url_token do
    collection do
      get :search
    end
    member do
      get :following, :followers
    end
  end

  resources :events, param: :url_token, shallow: true do
    resources :comments, only: [:create, :destroy]
    collection do
      get :search, :autocomplete_search, :golf_course_info
    end
    member do
      patch :invite
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :participants, only: [:create, :destroy]
  resources :notifications, only: :index
  resources :event_invitations, only: :update

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/layouts/_footer.html.erb
<footer>
  <p class="text-center"><small>Copyright &copy;<%= ApplicationHelper::WEBSITE_NAME %>, All Rights
      Reserved.</small></p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white">
  <div class="container">
    <div class="d-block d-lg-none">
      <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
        aria-expanded="false" aria-label="Toggle navigation" style="border-color: rgba(0,0,0,0);">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= render 'layouts/header_logo' %>
      <div class="collapse navbar-collapse bg-light" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item p-2">
            <%= link_to(events_path) do %>
              イベントを探す
            <% end %>
          </li>
          <li class="nav-item p-2">
            <%= link_to(users_path) do %>
              ゴル友を探す
            <% end %>
          </li>
          <% unless user_signed_in? %>
            <li class="nav-item p-2">
              <a href="#" data-toggle="modal"
                data-target="#modal-<%= ApplicationHelper::EASY_LOGIN_MODAL_MODE %>">
                お試しログイン
              </a>
            </li>
            <li class="nav-item p-2">
              <%= link_to 'ログイン', new_user_session_path, class: "text-info" %>
            </li>
            <li class="nav-item p-2">
              <%= link_to '会員登録', new_user_registration_path, class: "text-info" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="d-none d-lg-block w-100">
      <div class="header-logo float-left">
        <%= render 'layouts/header_logo' %>
      </div>
      <div class="header-menu float-left">
        <ul>
          <li class="mr-3">
            <%= link_to events_path, class: "text-info" do %>
              <i class="fas fa-golf-ball mr-1"></i>イベントを探す
            <% end %>
          </li>
          <li>
            <%= link_to users_path, class: "text-info" do %>
              <i class="fas fa-user-friends mr-1"></i>ゴル友を探す
            <% end %>
          </li>
        </ul>
      </div>
      <% unless user_signed_in? %>
        <div class="header-right">
          <ul>
            <li>
              <div class="loginbtn">
                <button type="button" class="btn btn-outline-secondary rounded-pill btn-block"
                  data-toggle="modal" data-target="#modal-<%= ApplicationHelper::EASY_LOGIN_MODAL_MODE %>">
                  お試しログイン
                </button>
              </div>
            </li>
            <li>
              <div class="loginbtn">
                <%= link_to("ログイン", new_user_session_path,
                  class: "btn btn-outline-info rounded-pill btn-block text-info") %>
              </div>
            </li>
            <li>
              <div class="loginbtn">
                <%= link_to("会員登録", new_user_registration_path,
                  class: "btn btn btn-info rounded-pill btn-block") %>
              </div>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="header-right-login">
        <ul>
          <li>
            <%= link_to notifications_path, class: "text-secondary" do %>
              <span class="fa-stack">
                <% if unchecked_notifications.any? %>
                  <i class="fas fa-bell pt-2" style="font-size:30px;"></i>
                  <i class="fas fa-circle n-circle fa-stack-1x"></i>
                <% else %>
                  <i class="fas fa-bell pt-2" style="font-size:30px;color:lightgrey;"></i>
                <% end %>
              </span>
            <% end %>
          </li>
          <li>
            <%= link_to user_path(current_user), class: "avatar-user-name nav-link mr-3 p-0" do %>
            <% end %>
            <div class="dropdown">
              <button type="button" class="btn setting-btn py-0 px-1", data-toggle="dropdown",
                data-offset="0,10", aria-haspopup="true", aria-expanded="false", style="box-shadow: none">
                <% if current_user.avatar?%>
                  <%= image_tag current_user.avatar.url, class: 'avatar-img-mini rounded-circle' %>
                <% else %>
                  <%= image_tag 'fallback/default_user_avatar.png', class: 'avatar-img-mini rounded-circle',
                    :size =>'30x30' %>
                <% end %>
              </button>
              <div class="dropdown-menu dropdown-menu-right dropdown-font">
                <%= link_to user_path(current_user), class: "dropdown-item d-flex align-items-center" do %>
                  <i class="fas fa-address-card"></i>
                  <div style="width: 100%">&nbsp;マイページ</div>
                <% end %>
                <%= link_to new_event_path, class: "dropdown-item d-flex align-items-center" do %>
                  <i class="fas fa-plus-square"></i>
                  <div style="width: 100%">&nbsp;イベント作成</div>
                <% end %>
                <%= link_to edit_user_registration_path, class: "dropdown-item d-flex align-items-center" do %>
                  <i class="fas fa-edit"></i>
                  <div style="width: 100%">&nbsp;プロフィール編集</div>
                <% end %>
                <%= link_to destroy_user_session_path, class: "dropdown-item d-flex align-items-center",
                  method: :delete do %>
                  <i class="fas fa-sign-out-alt"></i>
                  <div style="width: 100%">&nbsp;ログアウト</div>
                <% end %>
              </div>
            </div>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
  <%= render 'layouts/modal',
                {modal_id: ApplicationHelper::EASY_LOGIN_MODAL_MODE,
                mode: ApplicationHelper::EASY_LOGIN_MODAL_MODE, object: nil} %>
</nav>

app/views/layouts/_header_logo.html.erb
<% if user_signed_in? %>
  <%= link_to ApplicationHelper::WEBSITE_NAME, events_path, class: "navbar-brand font-weight-bold" %>
<% else %>
  <%= link_to ApplicationHelper::WEBSITE_NAME, root_path, class: "navbar-brand font-weight-bold" %>
<% end %>

app/views/layouts/_modal.html.erb
<div class="modal modal-default" id="modal-<%= modal_id %>" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <br/>
        <% if(mode == ApplicationHelper::EASY_LOGIN_MODAL_MODE) %>
          ログインすることでこちらのサイトをお試しになれます。
        <% elsif (mode == ApplicationHelper::DELETE_USER_MODAL_MODE) %>
          このユーザーを削除しますか？
        <% elsif (mode == ApplicationHelper::PARTICIPATE_EVENT_MODAL_MODE) %>
          このイベントに参加しますか？
        <% elsif (mode == ApplicationHelper::STOP_PARTICIPATE_EVENT_MODAL_MODE) %>
          このイベントの参加をやめますか？
        <% elsif (mode == ApplicationHelper::DELETE_ACCOUNT_MODAL_MODE) %>
          本当にアカウントを削除しますか？
        <% elsif (mode == ApplicationHelper::DELETE_EVENT_MODAL_MODE) %>
          このイベントを削除しますか？
        <% elsif (mode == ApplicationHelper::REJECT_EVENT_INVITATION_MODAL_MODE) %>
          招待をお断りしますか？
        <% end %>
        <br/><br/>
      </div>
      <% if object.nil? %>
      <div class="modal-footer", id="modal-btn">
      <% else %>
      <div class="modal-footer", id="modal-btn-<%= object.id %>">
      <% end %>
        <button type="button" class="btn btn-sm" data-dismiss="modal">キャンセル</button>
        <% if(mode == ApplicationHelper::EASY_LOGIN_MODAL_MODE) %>
          <%= form_with(model: resource, as: resource_name, url: session_path(resource_name),
            html: { method: :post }, local: true) do |f| %>
            <%= f.hidden_field :email, {value: 'guest@example.com'} %>
            <%= f.hidden_field :password, value: "guestpassword" %>
            <%= f.submit "ログイン", class: "btn text-info btn-sm" %>
          <% end %>
        <% elsif (mode == ApplicationHelper::DELETE_USER_MODAL_MODE || mode == ApplicationHelper::DELETE_EVENT_MODAL_MODE) %>
          <%= link_to "削除", object, class: "btn", style: "color: #f90e43;", method: :delete %>
        <% elsif (mode == ApplicationHelper::PARTICIPATE_EVENT_MODAL_MODE) %>
          <%= form_with(model: object.participants.build, local: true) do |f| %>
            <div>
              <%= hidden_field_tag :event_id, object.id %>
            </div>
            <%= button_tag(class: "btn like-sm rounded-pill d-flex d-sm-none align-items-center justify-content-center px-3") do %>
              <i class="far fa-thumbs-up" style="font-size: 1.1rem;"></i>
            <% end %>
            <%= f.submit "参加する", id:"participates-event-btn",
              class: "btn text-info rounded-pill d-none d-sm-flex align-items-center justify-content-center px-3" %>
          <% end %>
        <% elsif (mode == ApplicationHelper::STOP_PARTICIPATE_EVENT_MODAL_MODE) %>
          <%= form_with(model: object.participants.find_by(user_id: current_user.id), html: { method: :delete }, local: true) do |f| %>
            <div><%= hidden_field_tag :event_id, object.id %></div>
              <%= button_tag(class: "btn unlike-sm rounded-pill d-flex d-sm-none align-items-center justify-content-center px-3") do %>
                <i class="fas fa-check" style="font-size: 1.1rem; position: relative; top: 1px;"></i>
              <% end %>
            <%= f.submit "参加をやめる", id:"stop-participates-event-btn",
              class: "btn text-danger rounded-pill d-none d-sm-flex align-items-center justify-content-center px-3" %>
          <% end %>
        <% elsif(mode == ApplicationHelper::DELETE_ACCOUNT_MODAL_MODE) %>
          <%= form_with(model: object, url: user_registration_path, id: 'delete_user', class: 'delete_user', method: :delete, local: true) do |f| %>
            <%= f.submit "削除", class: "btn text-danger btn-sm"%>
          <% end %>
        <% elsif(mode == ApplicationHelper::REJECT_EVENT_INVITATION_MODAL_MODE) %>
          <%= form_with(model: object, local: true) do |f| %>
            <%= f.hidden_field :invitation_status, {value: EventInvitation::REJECTED} %>
            <%= f.submit "お断りする", class: "btn text-danger btn-sm"%>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application' %>

<link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/jquery-autosize@1.18.18/jquery.autosize.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>

<meta name="viewport" content="width=device-width, initial-scale=1">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="javascripts/respond.min.js"></script>
<![endif]-->

app/views/layouts/_toast.html.erb
<% if notice %>
  <div aria-live="polite" aria-atomic="true"
    class="d-flex justify-content-center align-items-center fixed-top mt-5">
    <div class="toast bg-success text-white" role="notice" aria-live="assertive" aria-atomic="true">
      <div class="toast-body">
        <%= notice %>
      </div>
    </div>
  </div>
<% end %>
<% if alert %>
  <div aria-live="polite" aria-atomic="true"
    class="d-flex justify-content-center align-items-center fixed-top mt-5">
    <div class="toast bg-warning text-white" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-body">
        <%= alert %>
      </div>
    </div>
  </div>
<% end %>
<script>
  $('.toast')
    .toast({
      autohide: true,
      delay: 2000
    })
    .toast('show')
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta http-equiv="content-language" content="ja">
  <title><%= full_title(yield(:title)) %></title>
  <%= favicon_link_tag('favicon.ico') %>
  <%= render 'layouts/rails_default' %>
  <%= render 'layouts/shim' %>
</head>


  <body class="bg-light">
    <div class="main-container">
      <div class="bg-mask">
        <%= render 'layouts/header' %>
        <%= render 'layouts/toast' %>

        <%= yield %>
        <%= render 'layouts/footer' %>
      </div>
    </div>
</body>

</html>